<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="DESKTOP-P8RTCON" name="com.qa.bigbazaar.test.SavedCardOrderPlacementTest" tests="6" failures="0" timestamp="19 Apr 2021 08:16:54 GMT" time="2.610" errors="1">
  <testcase name="setUp" time="2.610" classname="com.qa.bigbazaar.test.SavedCardOrderPlacementTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.bigbazaar.base.BaseTest.setUp(BaseTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase name="testLoginVerifiedText" time="0.000" classname="com.qa.bigbazaar.test.SavedCardOrderPlacementTest">
    <skipped/>
  </testcase> <!-- testLoginVerifiedText -->
  <testcase name="testAddressText" time="0.000" classname="com.qa.bigbazaar.test.SavedCardOrderPlacementTest">
    <skipped/>
  </testcase> <!-- testAddressText -->
  <testcase name="testItemsAdded" time="0.000" classname="com.qa.bigbazaar.test.SavedCardOrderPlacementTest">
    <skipped/>
  </testcase> <!-- testItemsAdded -->
  <testcase name="testSelectDeliverySlot" time="0.000" classname="com.qa.bigbazaar.test.SavedCardOrderPlacementTest">
    <skipped/>
  </testcase> <!-- testSelectDeliverySlot -->
  <testcase name="testPayuOrder" time="0.000" classname="com.qa.bigbazaar.test.SavedCardOrderPlacementTest">
    <skipped/>
  </testcase> <!-- testPayuOrder -->
</testsuite> <!-- com.qa.bigbazaar.test.SavedCardOrderPlacementTest -->
